cable:
  filename%restart_in               : ""
  cable_user%CLIMATE_fromZero       : .TRUE.
  cable_user%YearStart              : 1841
  cable_user%YearEnd                : 1870
  icycle                            : 2
  spincasa                          : .FALSE.
  cable_user%CASA_OUT_FREQ          : "monthly"
  cable_user%CASA_fromZero          : .TRUE.
  cable_user%CASA_DUMP_READ         : .FALSE.
  cable_user%CASA_DUMP_WRITE        : .FALSE.
  cable_user%CASA_SPIN_STARTYEAR    : 1850
  cable_user%CASA_SPIN_ENDYEAR      : 1859
  cable_user%limit_labile           : .TRUE.
  casafile%cnpipool                 : ""
  cable_user%POP_fromZero           : .TRUE.
  cable_user%POP_out                : "ini"
  cable_user%POP_restart_in         : "<home>/stage_1_climate_spinup/<run>/restart/pop_ini"
  cable_user%POPLUC                 : .TRUE.
  cable_user%POPLUC_RunType         : "static"
  cable_user%c13o2_restart_in_flux  : ""
  cable_user%c13o2_restart_in_pools : ""
  cable_user%LUC_restart_in         : "<home>/stage_1_climate_spinup/<run>/restart/LUC_rst.nc"
  filename%restart_in               : "<home>/stage_1_climate_spinup/<run>/restart/climate_rst.nc"
  casafile%cnpipool                 : "<home>/stage_1_climate_spinup/<run>/restart/casa"
  cable_user%c13o2_restart_in_flux  : "<home>/stage_1_climate_spinup/<run>/restart/c13o2_flux_rst.nc"
  cable_user%c13o2_restart_in_pools : "<home>/stage_1_climate_spinup/<run>/restart/c13o2_pools_rst.nc"
  cable_user%c13o2_restart_in_luc   : "<home>/stage_1_climate_spinup/<run>/restart/c13o2_luc_rst.nc"
cru:
  rainRecycle                   : .TRUE.
  lwdnRecycle                   : .TRUE.
  swdnRecycle                   : .TRUE.
  presRecycle                   : .TRUE.
  qairRecycle                   : .TRUE.
  TmaxRecycle                   : .TRUE.
  TminRecycle                   : .TRUE.
  uWindRecycle                  : .TRUE.
  vWindRecycle                  : .TRUE.
  fDiffRecycle                  : .TRUE.
  CO2Method                     : "1700"
  NDepMethod                    : "1850"
luc:
  ClimateFile                   : "<home>/stage_1_climate_spinup/<run>/restarts/climate_rst.nc"
  YearStart                     : 1700
  YearEnd                       : 2022

